# Какая локаль грузится из /lang/messages_<locale>.yml
locale: en

shop:
  menu:
    title: "&aPirate Shop"
    description: "&7Buy lethal beauties & treasures"
  items:
    - type: SWORD
      id: CUTLASS
      price: 500

second_page:
  items:
    - type: SWORD
      id: CUTLASS
      price: 500